// shared/proto/lobby/v1/lobby.proto
//
// LobbyService — owned by match-service.
// Used by: match-service internally when forming a ranked match.
//
// CreateRankedRoom is the critical synchronous call: the queue needs
// the room_id and join code to include in the match_found event sent
// to both players' WebSocket connections.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lobby.proto

package lobbyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRankedRoomRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PlayerAId string                 `protobuf:"bytes,1,opt,name=player_a_id,json=playerAId,proto3" json:"player_a_id,omitempty"` // UUID — will be seated at seat 0
	PlayerBId string                 `protobuf:"bytes,2,opt,name=player_b_id,json=playerBId,proto3" json:"player_b_id,omitempty"` // UUID — will be seated at seat 1
	GameId    string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`            // e.g. "tictactoe"
	// MMR of both players — used to set turn_timeout and game config
	MmrA          float64 `protobuf:"fixed64,4,opt,name=mmr_a,json=mmrA,proto3" json:"mmr_a,omitempty"`
	MmrB          float64 `protobuf:"fixed64,5,opt,name=mmr_b,json=mmrB,proto3" json:"mmr_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRankedRoomRequest) Reset() {
	*x = CreateRankedRoomRequest{}
	mi := &file_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRankedRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRankedRoomRequest) ProtoMessage() {}

func (x *CreateRankedRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRankedRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRankedRoomRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRankedRoomRequest) GetPlayerAId() string {
	if x != nil {
		return x.PlayerAId
	}
	return ""
}

func (x *CreateRankedRoomRequest) GetPlayerBId() string {
	if x != nil {
		return x.PlayerBId
	}
	return ""
}

func (x *CreateRankedRoomRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateRankedRoomRequest) GetMmrA() float64 {
	if x != nil {
		return x.MmrA
	}
	return 0
}

func (x *CreateRankedRoomRequest) GetMmrB() float64 {
	if x != nil {
		return x.MmrB
	}
	return 0
}

type CreateRankedRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       // UUID of the created room
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"` // short human-readable join code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRankedRoomResponse) Reset() {
	*x = CreateRankedRoomResponse{}
	mi := &file_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRankedRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRankedRoomResponse) ProtoMessage() {}

func (x *CreateRankedRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRankedRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRankedRoomResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRankedRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRankedRoomResponse) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

var File_lobby_proto protoreflect.FileDescriptor

const file_lobby_proto_rawDesc = "" +
	"\n" +
	"\vlobby.proto\x12\blobby.v1\"\x9c\x01\n" +
	"\x17CreateRankedRoomRequest\x12\x1e\n" +
	"\vplayer_a_id\x18\x01 \x01(\tR\tplayerAId\x12\x1e\n" +
	"\vplayer_b_id\x18\x02 \x01(\tR\tplayerBId\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x13\n" +
	"\x05mmr_a\x18\x04 \x01(\x01R\x04mmrA\x12\x13\n" +
	"\x05mmr_b\x18\x05 \x01(\x01R\x04mmrB\"P\n" +
	"\x18CreateRankedRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode2i\n" +
	"\fLobbyService\x12Y\n" +
	"\x10CreateRankedRoom\x12!.lobby.v1.CreateRankedRoomRequest\x1a\".lobby.v1.CreateRankedRoomResponseB5Z3github.com/tableforge/shared/proto/lobby/v1;lobbyv1b\x06proto3"

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData []byte
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)))
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lobby_proto_goTypes = []any{
	(*CreateRankedRoomRequest)(nil),  // 0: lobby.v1.CreateRankedRoomRequest
	(*CreateRankedRoomResponse)(nil), // 1: lobby.v1.CreateRankedRoomResponse
}
var file_lobby_proto_depIdxs = []int32{
	0, // 0: lobby.v1.LobbyService.CreateRankedRoom:input_type -> lobby.v1.CreateRankedRoomRequest
	1, // 1: lobby.v1.LobbyService.CreateRankedRoom:output_type -> lobby.v1.CreateRankedRoomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
