---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAs33U/6oAbBkr7VCoIZDKxkWWMd+rvWlklQ+eEXK/K38CRQZ4xrdlpXg4Prb23BzMLu9FU9ZQX8LMuJdwrPGFB0VbrCJOTIRdPUfS+z9CpVZjk6c3dQqX535Ujl4BUyUFMtSwc6d021TbadLhvBuOq4nH86eUeueOwIeDf+tLgcQuOUuFgfhBZCi/VgQuQFnR9z+nhaMHNR+KQgB7F4GbAHFpjX8//nTtFAm1WgcqyLjEPmd8HF7Kcq50Xz9LrUOO9jFi67oIy6RX/vY60yIgJMPgcWGJ2Ai8ZdhcgZpOyPFlM1HS7H46/jCg4BCjgyl0R9t+17aey9NcwBOJcnMKNKzSCOUZSnjiLzNJQBuwzBniEIqLsIfjjS2RY4mh946u8qDAC5XQc4xrjYhg8YqKzK3lnMbfePA6CAL3pIKD2npi4wd/R9flSzftTAM2+vxIfd2FA6rEyBILNbxGSuDAOb4Bsxnisxxmcfx+gLa8h73AldbJlW2DoRa7QpJJAmj5BehREFCFRUL1xAxgVZ5fxkjtqiuSyA1W2Olw87JzABTgA5Lgor3Xk0/Dcj1UT6q8aqULp6XWi12/bdHJ1YPg0hRrntX0z1L+ptrjGkorWpDQclKpPrwvMJI9TkD6d8K4XU2NxpPORjzdnkxdrIhq+l/qbCPUDHFRQ5yIwAfdWa3bc2/Dw8faQdLnR4x9IRy1xAwoQwjwimb458ej8oBWh2okztFo97Cczemm+VJE823p4SlF7/8ukIS1aqU3HtirLK9eRjmTnjUc7tgUidJD4y5Z7CHsPaOVownTpIGS8x3pI7xF/u5pG862PeKkrdmaGPGRqIf9YqCgKBf1o3gQUiEizAm5AfNzY5t8+B5Uk+ip5vwHvszplkW0Sa6Qq3ZXX4MkBcOXOGkppL5gNVnGQzEWwirN/JnxgsMGwXp/V2Z6jut7a+mRy
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
