---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-auth
  namespace: recess
spec:
  encryptedData:
    DATABASE_URL: AgB58jNLKA3exeQuiFnRhQAOVdqtoKuL21wBKTxpImHrOlV6JPNPiwtQgIBWG52uMQFPGcwf5uQeMikoiRQqf+piJIX0nduHwZMZP/voeECUFQZcVj/KHJShSwXBqe8w+OCnC/sGBS//GtKsAu52/PvB1U5ft5eCVAEAnLJ37E7tkxkd56iroB0HM7ZCOBG4lXPcBho25uItjvjfuWAFodyNOgoDb5paZUBRiNPMb2KCdEk/afMEBrzEWVTx3fNwC7u7XfgCFYRhrQY8DJ1RTNxN/vbt3xPJ535bOYx7U6y4dtIq4MDAEj865DHG/Gl0jcvT7gi6Lqq1jdCBnyMNXgOTKf/sAFOm5KmtqE35G9eKawKdNcFYohXZb3WPrexir7eTqXTsW/X1nofS8GCIuOscJDQSOXDUVGW2DP2B1SeWhaBuApYKEJylPxGBqJ9774SDvjkvoEoVJOlwq50ESZzVFPWxKKRdT479cMw6bexH4f5dJ1sbZYlv5mbn3w8wUB451O9ujWMv0Ikt2s5lEmfhW+onUUpCFV4t39Uw/OV6sd6gMvJYhEbNKv4C8etSouR1Q1pL1IbqD8CjVpGlqzunkP1wA6wksUXbUoIIjBi2wHYHMq8efKskZYLsvJYp2LdjuvMrOH9FMi+bdfKSslU9oy5atY/tGx8GWq3MZTXcfG8z6+SHf+gseSi/sR/Tae5pJpeI9P8jGsHlNch9FMkH0OtuoPaUDMRSolZdmc6Pp+jNZATtJAWOCEppRKT+nt8YK7zfaRQXgNRPl+qFbjxJco1e3xEsYF+cnALINS3ZbJ7uiOqgvJSCsnMv/Ga2jAQef5RUyFstogOztPwFBusovBPVeEKcfYW7mqnnusxdCaou41bC6UpWo+GoW05b+9G5zKpk
  template:
    metadata:
      name: db-auth
      namespace: recess
