---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-auth
  namespace: recess
spec:
  encryptedData:
    DATABASE_URL: AgCjVvGvfW67SpHHeuXz20PH7cZqbNWnhbSkfLF0pmQlopY4OPLC+rshU5p0GVrwRuGNumpw719YFtyFO0EZTQ3H3je4rDWXpncNznpRM9eXSwDZ4h9khI3SotfeY7Kxhx/fhRBhaiVQWw4CV9yLYjMp1v+FJArgie3dk3MGhJoOtIvMmO0W6q/ko819/9iHyDW9wNS8oSrNJDPXNYvr/sAR0ArgIHITTARYSHmARI9KYEqiFCTJVxnK5weHYVUMApsBIkRaG0s8srDmXIlusthHYm4L17Q0uyIp5UwxTHaZLzXGYiAnGY5rva4hfYdAlU7Mu1vahdOL6f6+kGgr8e6xWM60yBVCjZ/sLxW+BxuxBhj6+X3BU+ssgWAFxeJwhVOLTt9qjGjcxSd25OGrTauGbbgi0bLbxhCrfXwxlmvrcJ3ArMBd13Mdh6hFe40OhllN7pdbInacQnxgrfqrkzQoenzhKIwMkTGiJIpjYa6I37X5rab7Z76i7RU6SwkcURM/gxhO9Veh3J0ZAQARkEkU/1ZRhP3TeOKUtbDWg+G1rI7FPOINJi8SKMBNmVTBBQYwbKt8aWtm+nkly2Rw0BP97+H3F7MHZDTBh9ijaKOdzHIgyhNzimwzDIolGyJph5JoPk4Vu/NGeG0ljfd8zoM2FDubunLncB/vg8B9hocUcbgGTybcjfecwDWOS5zg7LbaNSbawun1Q78R+yVSIDtFYwv+3RjxmvrsaTV6We6P3Ha3UjDdj8/+AP8EI5LoQDlMN+7Ga5u9B7fs0DE/va4ctLp5ZbnB+GhVjbxKSUF208feGKYpGPkMxUMirbmJLTTm5wC6IJfBZKMkh3cBQhchtuuibYJNk4n3iipUFFfU5bfuYD32T/LKOndo8p2+90yKVumI
  template:
    metadata:
      name: db-auth
      namespace: recess
