---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth
  namespace: recess
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAT+v7275MXlNRwAS7WSmXZEoQjXhZoxDZzNCg32WZLjSEVLlTbGb1SA4UZc2l1vMRz1bUwL8yACrYq4kighlIAHSLh8nCwCeEje+rpvqbGJDvlNR7PHMnq038D1M3K89hfbVcKETZBAwmZhZVBe66hH8ehWWNk0/KIJgre+M0qmCipE2OLqN8ONpjs0HUaEHtUI9gbfvB4c0EEBCbloqSIC9/uVI43lqpGUPQZrKXV5O3nsZWKWex43I3wen6U2BX5VYnlX8Rqync4Nx/RreD8uC/S5coIFYqwAYRk4XPd/6smQ8LoR9QlIQFxleGI4JOsGkAKBqtc6gWaUyom4hErggZRA/k7Byk2b9YqKFckJDsbX+/qw1pe1WV3JWYsci0+tOW0rcrRwlkxBQUnhQfcuZHzuM3dIl+iNGor9plu1nRLoz4kFCALiP5V+CDOeTe8N7K1MqU+S3/jgo6bg1QxPMsEYKonIZ7BJ1fwuaaGtmfFp2rlyZhxxVSuzVXKsYADPaqk+E4g1uWIwKRE77tBZ4qCr1sX9yvXhU0Rca7tspMI3KL3bvELOLI54SM5BWAlXwKk3G7jJhXdhXyKFUi5PzN5Sfi4Y3nGPqn/c0uKWVH5bCqRfFlWBrozlG2oAJ+T2QeZdK8KD5rrCyaAptrf5uRxFjQRc/+FfR3ii3XccTPhFDQumy8+DUU5w/IbV35N7kO3Z9K4cJPa6EOBiXuCrS2VNw==
    GITHUB_CLIENT_SECRET: AgA6ZXzdd+DREbMp62JvYTC9YVYPs4ji04WZ2nMse41I7kV/pQP344du9bxyCdm1cl9ia/q5XDYSEV3n8ZIcmVQ8vDsrjJheV1Hv2JvaKnfAWzmkaJYKzA2i8VKq9UB9K7cfanDlCXmNiqL+8yQ2Hzq9CEqxHo/tUcKXQMb4e1cUGoWHDq/jf3ivOk9JcZ6sQfwxACSs9LDsmKpjbfz9Tj/wYcOzYWATCVvx7mGy2H6LgWoH2lzQ8xkUmofyH8ZE2EOtFkTnoD+wdUSH71GrHeucwfEmyJigyarfRFrAJDT1dcHWXj0RYMvtveqlY2W3goAoHs7LQHcVEpaJTumYThQ3xGAybPULeZStB980BdzyiCSSBJE2zYD8LxCwQ0AHGcmwc75VwMW6jcJ3kUE9EApiwFl84Dp8Y8kf+4QIXSudBFnPH7AeO7/pdKY/PbZsvXMh9igYKatYNvaGPvZCnTXwuIe4GWruDSSMlO+rgEyTN2BVMubuU8nQTNBaassZmx6UZvE9A7YJvdvbg9+0Pe3JX0fqjSQA4RVNPiIE8unYRBE4Py26xrZZKDGfTRqjaWgRgMF0sI3j/m/P5dPU2WGh8XacOhgeGXbYPYoTMmUNeS+nL+GRFWQkPlcMu2fKzmM4vNEz2mKI0J5fOcqxNvEzmstliTnlixzGltNUq4kZY5cU479c4IX54S5Af+wFwjAG3+eS5wqUYg8USxTWyH5tXjcOrJN0wZoDblvbAGMctC1f0G0Ou3L2
  template:
    metadata:
      name: github-oauth
      namespace: recess
