---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgC2WUq7+wvYHKn/p1xXae4rDPxDWz6Uf9kkamw1WXIWsGpnQv8pL+eG2DbxUNJBtbwdQvzo11J8gtIn1naNWvlYg+CU8aanoUXXCtAH4d0ogRWlrgSAxQ/fE5h8jDCTKXtr5jMuoYuKz2iLWPahG89ExC0xb93nKEUUVIphby4UgBmD8ZdP4B6hxhGze+Kx8POeIN33UPSz2Nr6eybDJa8V7R2npOW8fhPJy4KdwfwPdcc7tw+cEONYiUO8/NUpJ8hRJ5irV0v8V9ttxiMWlAUBx43wK4Yvl1irbPbNAHQu7MX4TkZkpr8HTZ6rlI/6RTuAE0xUPai7tk3Gy1YS/rD2+BxE2w+nYzTVraOwandjMksmZbbUagGoX5tqc3uoxlZkcJlhDoqfxhN13mcZaZCDlmfc8CBSY0odfRKMgIeJGdIvF+b2sPZnj6S77Qep9adh0y3ArqUy7G7pXtfCxOrqjsY2Oi5p+DNOjSH3HkquwAW4ZQdZEqPjD3Zc4zvP12p5lOWJKOLwRajeT8fSF+YAxRGg1k4BxeERn/yC/VvGSOxdjVqduHoOJUC7ZiAAxNcfQLIu2k+Vq/oXvIPCHN8lsVIZ8yUWQcScDMZzfLYiQCOF0UMWVCu7Wju+OpZGPzRQe5icBopDCGy8AdXW1x0YO1Ns1i28u//t0gHfz9gWayqhvc0N+BZma8m5dbPFPe4AprudZet2a2bC1eemC/3dC7IPFA8eFdZmJfNVA5pPJg==
    admin-user: AgBV8E5TiBntKMJcd0NpAch+sNsvIibHqQwA9MulTRkbEwbs20CxODZ8dn4NF3Ny+sGp6IQrHhQWrirrlY3lCAc+gFAyoTDqxgTq3RJvMiKM1LpzOucutJ8p9DkzpSQsHiPSsTsRIL3y7jlYfWRhiuVuC0tDV1MpNKcrmBxKpdjskyxtzn/L40wH8eAAOcYEo+BxdDcXfcx2Dq1hvnxwuSwAztPFJwIjjV6Y/mkUgDcZK4iHPXHJ6+spUU+Sh1u7MZHa0uLyL+TUqcKYvjA6+Ie99I5ePeJ5f5dcZPVDPyHrLTW3xwpDoQqsnukpXngcSc1qS15jsTtaN/Uj8/GZmCq6d06AxVBfDZOA8xkTHyFdjjX1zvlqvEFHqS1JBnNEG4FDveNze2+/8ud8MyAADgOENPYjV6SXM13KIilMOBjM+QaLX3p47e0svgQxTRwFZt9T7/oYwNwZlh8C2RlGztmADJPs4y983HfABNTYhmE9pBkg51ilgTfTrBev7bGUC4lhlLvShrgTrGY43vQjoADJs+GXvNtZEKHfZnsignAPcFcc5vJNFbsAs9d6VfasdFGcDuOjbZ9Wu6zXthAYz8kZnpzxnkwxmGAJCPFmXaCqtjC2Ms7Jwe+1G7FrI/52fBolHHk6/aW/Zea6Qnqr876Eka/h0zRtHvoYuDzOSl55mGie/3CMItSI0QeJRidFfIzeL68N2A==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
