---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt
  namespace: recess
spec:
  encryptedData:
    JWT_SECRET: AgCmgf7rDeG0CG+wUXklE/4rOCnO9hmKJlOUDAUwwPGz8GcNFUruB11YFznfjUDdjCUiAMxmoenKzjcXcQX75yFtfEmEmXvY8k3x6D/9oGeURiDbirMxvbD9cXR8BgqeMjcytNbfpszobhIi0S30Mg8ic4XcAZ+psp5HAJy7Ei8t6qCzfy2hHC0Poam/2Vn4rrb55V2B/GM1uPrQl5mVXFEHIkMLU3Wc29XwgGuD8Aw/o3a6VvBGrkjEOTPYnbu/LpyFIQoAwG0weJ9Pig5waWpMG1E0A/EVGEONMtOaXjxzuntCeQjddmNs/eJmd46eg6UNNGL4AhKVt2CAWAqP6ee9s83ncecs54q0/3vJjeEgl2YhM03+Vj4cCbqzhWpC0nMvLdPivC7NhgjNhczvyab3YFPnJyNtTghznU6XLmpy9TLTkESInz35IlXrdtjo1SVrq//MhEyAz2qlnP4Ma6pnIeZSPBvYnW2Iu1L7PqqUWnYLe/yji5Yv1grgB+Cd5civgs7635qFKL4scj8/0rMU+Bq5FwDnh8SFvgHDNM4cmJBCihFJ5NWWGaDOzb8MWr2Ny+EsH4zzLDU3cpbZ1yriCGpEVFEWNwCBEhkR6sG+ZW8EyCcPzqHH+P5zwm8rUHJQb5PVhUgw6mCamo/iDhDM1xdxmw7979OBjTSKxdmAFVjyi/iLazp1RzO+KTt9P/3yGH2aCPO6DnSDuQ78JopL0lVBTmEiyJrDrFsLrMZsKAWByWhSofzVhw5dz9R5TOCM+I3gKxR+IITBsOlT0yiL
  template:
    metadata:
      name: jwt
      namespace: recess
