---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jw
  namespace: recess
spec:
  encryptedData:
    secret: AgB1GU0+KOIV3Ef7Q01sDjnY2TN08bwWgCWIAmYy5LF/B0vrtkRCuUJJ5KqDUgmRTq3O1N9XanvdOy2PvqqszqU7UY61vjB03X9glHC7VpED7/25QW9nN9DhHczlZGwR9tfCFfJJjnxq1mu87pNIyT2ALgZ1T8+24rtPE/SU0mAxW+tNo1R9PwXpxct+xo8MONCdYIg2AoAoDlujRz6SsiUlXDxSqLFQQblG8R/RxQT1JjYbKW3D1qvkfHhcREEcQEzUmZklWCDGpHzX/tbv648uWe+AJzP0HcaSB90MBlkSdw2EgyS8yAK9N7Yb2kdeZmDneJe66AXWVgfIfzo39DqZ549O2JIPEQ7lFiy5tS+dUIAWKJ0vp1wZ8VwEbIx8LuSHK2wIt+80Rvz6a9RLtG2RqImNPo+NNSU/M6M14GG9+0Q0otlGAvvpF3Vg8oYPrGf9/+wNefobxd5BLa4w2yoj3bWORRYWAKLG2KuH+8X+39G+Pg1pfFp48qu3JamgF7rhx3nsbgTlJfRyMMICS/P15Zxj4CdRS4VTQV5BF200bN/8eLNczOVzAZxGuLPyK0F5e7IEHsygN5HWy175esi0M2MCeneNrB52n1po5bOgKRxfmI1mfaTz/4WTN7roEiUDzRKybTllf4y7JLufeDrjdiA+YlLsLEBi/cJRZu9DQuPQXtsQVyZMiCehlu4M2IAb7KMT2suDIk5s3uqJJKj7WmQxoSOI+FNXPKV1oIVnGUDMs4oGTMCzlOLED4aBOHW3VovcyCLAxQflhmN6uL1g
  template:
    metadata:
      name: jw
      namespace: recess
