---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: recess-data
spec:
  encryptedData:
    redis-password: AgA8GcH9yQpqU/K4ua1EdAWt0cKBdvE6yN/AW2UIaAKYcl12pQQJVsBIOPcSsXjFrIbXZdkXTrfNjpj18f63hiXkcb44L2cd3FK2huiQrM9bdw7wevs3oUhw405RnLFy4E3DhDwHehao3RFxrUtgpHEBw/QLgKnWr3VNxTawRwVnQZzyKQHEsYLiXg8c2ntHT2dguYBuicbpkVDS//KRyi1th2pU8Jvm3v+qO6YHBiOXSk92dzINgwkUZ2SgfpHSXcbdbk0ugRjmIqh4DKxB+qOxMhn7YENHAmWzzvdR5I8GlV1lshnB5ZGC2wwcdAyGdMXnKGiiu8FJ514iFemMXUVcVmWHOLqVVZPNKZsPtQJBP4J/s746CSDYlzuLFhrYayzL5J+AwrP8JHv0oAafYvxtJWUtlYPMN5bW7bgK3H6LRYaIoVwwOG9bA63pBiTPYQMgKcyHdyGzaw3i7BVjuWE5q06akMPaHro1ZFg5ThioI0gcPMDLHqmF5ZusCH2WBdvIQjA0RkUKoJr5EwiRReOi4ERTEprNIPoRYHrvLMtlhnnlP+kLGNWJKwQrEGlQcFumSB4eEYExqgV2WErToN5tX2D/c/AjApUN8MuRBh3K915wNJkuicPni7LBkFGB0WeyrgaaT4c0LSx7AvCEmw1ZMSzLtoVOQvkcwGZ0Pov+A8xjuKHKsicWEG8cXuCgfdD7Sm/yTNc7cgX/HbND5RObu2jyaIOH+OdVjAWMQUybirckRVNfSVPnXOK00A==
  template:
    metadata:
      name: redis-auth
      namespace: recess-data
