---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-url
  namespace: recess
spec:
  encryptedData:
    REDIS_URL: AgB7ZTz62wH09sqVcU/G1UDebcOIE7tM0KxXYuBIDkW+QImtTnUIb9yQrbRCPvwaS2IQU+/HcW8VZ7sVATkvxTu7Ah5oGIDQMm8ilHTh/U9u+ou/p8PLYAeQRkC2fN6SUhV//xU4+mjYT4t3LVgsFMRmOKSjF0JUUjJ9ShGx6FafXmYGAYGB9wTuFLQx0X716oJgU6v0yK+P62loAm0EQzlVjhANkahevz2K4l74bvFstWrBChCflYy+ysG6xzel6DUuVx4vLvKA3b2WejtEDd16bA/KY7SEYtCeZfLFGUqjwWnzPMLO1oVW4gR5d0zyOj27ChNJBREvvDjDbl5qjFaGNCZb9V3tncqoIVOda/Mar4j1x6+88D3tYawTEtTZFo675ok+cR9WjXt0h+kBvIt5vSKHGcW8l2eYKtn9lo0u3yg9rrvt+BzDqaf9jRpVLIU/hYqjNA8HpF+7/+hdCCI1n0Dnddh4x8Qk6X90JLxoFG8TN7fudBjdGh3RiHBBHay+dzuwNNtO0iwQVSjLRdQMBE+vIlts/NyQHd8wxDq0LyLNoyRC3wLJzP+MTHLVvYToJO2GtWmQIg3YJ7g/b7wDYQ82QgGsoG4gzUp+w4SHk3kvtHmiuW46oX8Pq6yiNXtCc1YfLnV5VZYWQhpjPCHrzMhBdAGVZJKGPauaPf9FcJ+LLODeO5cdxhomFz/zTH4ghO7b4sS/RzgzdVfIVPhBsLGvTbpTDWdw3A7fj1uyIExL+DC/UHSoVl1lsRgpBAmXZ1yDKg6FjRygxlSkdlX8wEw7I9w0DsR/4MICEGkfh6nOGOkTx/UTvjrCuJqxqXqIymSiDi5ve4dVf+HOIr2Fw/GvDTzXxKs=
  template:
    metadata:
      name: redis-url
      namespace: recess
