---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-url
  namespace: recess
spec:
  encryptedData:
    REDIS_URL: AgBPycrcNYioIjlaWdtdK/opVMp/Lcn1KYoPrEnrQIO1emx1MADJ71cP95cbJQ0mWPzFOaTtT07D/pJaYqtGHu4lKPeqcxYF4PiGb5K+aBgDevDMIvCMuGs59uNq5Vz8vSy2ImZ4cHAwDzrnif0l1JN00Do2cZzkqOvTm2XnUxG86sUgNqcRlUbc/+X0yKKoDJk456WD3uop24ZS5oyzG7nGd56lgj5PWaErqdMsi834Vjaz2n0Lnl3yBn3GmdW1F2rmDVmFtSKCOR0Chg/Fz7DqpcoxQBnKEWPc3DUShrcHpcH1rjn+cnjIZ35dHOfCNVirdKbJhYoNe/AV/OwEFPvFhlAMMaVVzt9SNvfZpf5PyNaHtJZUtf6reRPgghNWtGYIgA/u2fW5Yfxj+huUQ6yJ+FihU8alJG2eemuGViJJWoATrh0YBUyEOMBr2e53kdNTCj53rponarXo5ppwQftFXiAO9HyK14OdTUqP1UYbZ1mmo/8r7dMrIfKFAFaN3F4zZ8oibbH8pshD2svjMyG4PGuG2UZxAI27I24cT2aCog8lgc4kmAPt37mB/YBWVLBw3GF0nZucavyNR7GXTxyFPuW6AkaFTwz/cwgQx0dHG98rhiRjzWJtPjxnNoak9SeEhiGJRYPJi/ExcBYzUJBmPgsYJOSZGeDot/z+Kd8iBevDNsuyW5avJ6gl5+ksxBQIHkVBwWkYVFPf00qRlhMBFzFIKxVJZyp/RHS3/xC/uqHt9WYDiwaudtscImPPMcN+rgyuxWOMuaY84Xsi+9PfXudPwBMWz1s+GdpBNjpOy6ruNICbTzpu9KlZ5C/9Obel7GpNGzJF6JSdnbIY9Q==
  template:
    metadata:
      name: redis-url
      namespace: recess
