// UserService — owned by user-service.
// Used by: game-server (ban check on login + WS connect,
//                        mute list for chat filtering,
//                        friendship status for DM/room join validation)
//
// Only exposes what other services need. Write operations (ban, report,
// friendship mutations) are HTTP-only, handled by user-service REST API.
// gRPC here is read-only + lightweight presence checks.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: shared/proto/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckBanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBanRequest) Reset() {
	*x = CheckBanRequest{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBanRequest) ProtoMessage() {}

func (x *CheckBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBanRequest.ProtoReflect.Descriptor instead.
func (*CheckBanRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CheckBanRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CheckBanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBanned      bool                   `protobuf:"varint,1,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                        // empty if not banned
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339; empty if permanent or not banned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBanResponse) Reset() {
	*x = CheckBanResponse{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBanResponse) ProtoMessage() {}

func (x *CheckBanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBanResponse.ProtoReflect.Descriptor instead.
func (*CheckBanResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBanResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *CheckBanResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckBanResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetFriendshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerAId     string                 `protobuf:"bytes,1,opt,name=player_a_id,json=playerAId,proto3" json:"player_a_id,omitempty"` // UUID
	PlayerBId     string                 `protobuf:"bytes,2,opt,name=player_b_id,json=playerBId,proto3" json:"player_b_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendshipRequest) Reset() {
	*x = GetFriendshipRequest{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipRequest) ProtoMessage() {}

func (x *GetFriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipRequest.ProtoReflect.Descriptor instead.
func (*GetFriendshipRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendshipRequest) GetPlayerAId() string {
	if x != nil {
		return x.PlayerAId
	}
	return ""
}

func (x *GetFriendshipRequest) GetPlayerBId() string {
	if x != nil {
		return x.PlayerBId
	}
	return ""
}

type GetFriendshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                        // "none" | "pending" | "accepted" | "blocked"
	BlockedBy     string                 `protobuf:"bytes,2,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"` // UUID of the player who issued the block; empty if not blocked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendshipResponse) Reset() {
	*x = GetFriendshipResponse{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipResponse) ProtoMessage() {}

func (x *GetFriendshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipResponse.ProtoReflect.Descriptor instead.
func (*GetFriendshipResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetFriendshipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFriendshipResponse) GetBlockedBy() string {
	if x != nil {
		return x.BlockedBy
	}
	return ""
}

type GetMutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // UUID — returns all players muted BY this player
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMutesRequest) Reset() {
	*x = GetMutesRequest{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMutesRequest) ProtoMessage() {}

func (x *GetMutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMutesRequest.ProtoReflect.Descriptor instead.
func (*GetMutesRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetMutesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetMutesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MutedPlayerIds []string               `protobuf:"bytes,1,rep,name=muted_player_ids,json=mutedPlayerIds,proto3" json:"muted_player_ids,omitempty"` // UUIDs
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMutesResponse) Reset() {
	*x = GetMutesResponse{}
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMutesResponse) ProtoMessage() {}

func (x *GetMutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMutesResponse.ProtoReflect.Descriptor instead.
func (*GetMutesResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetMutesResponse) GetMutedPlayerIds() []string {
	if x != nil {
		return x.MutedPlayerIds
	}
	return nil
}

var File_shared_proto_user_v1_user_proto protoreflect.FileDescriptor

const file_shared_proto_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1fshared/proto/user/v1/user.proto\x12\auser.v1\".\n" +
	"\x0fCheckBanRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"f\n" +
	"\x10CheckBanResponse\x12\x1b\n" +
	"\tis_banned\x18\x01 \x01(\bR\bisBanned\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"V\n" +
	"\x14GetFriendshipRequest\x12\x1e\n" +
	"\vplayer_a_id\x18\x01 \x01(\tR\tplayerAId\x12\x1e\n" +
	"\vplayer_b_id\x18\x02 \x01(\tR\tplayerBId\"N\n" +
	"\x15GetFriendshipResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x02 \x01(\tR\tblockedBy\".\n" +
	"\x0fGetMutesRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"<\n" +
	"\x10GetMutesResponse\x12(\n" +
	"\x10muted_player_ids\x18\x01 \x03(\tR\x0emutedPlayerIds2\xdf\x01\n" +
	"\vUserService\x12?\n" +
	"\bCheckBan\x12\x18.user.v1.CheckBanRequest\x1a\x19.user.v1.CheckBanResponse\x12N\n" +
	"\rGetFriendship\x12\x1d.user.v1.GetFriendshipRequest\x1a\x1e.user.v1.GetFriendshipResponse\x12?\n" +
	"\bGetMutes\x12\x18.user.v1.GetMutesRequest\x1a\x19.user.v1.GetMutesResponseB3Z1github.com/recess/shared/proto/user/v1;userv1b\x06proto3"

var (
	file_shared_proto_user_v1_user_proto_rawDescOnce sync.Once
	file_shared_proto_user_v1_user_proto_rawDescData []byte
)

func file_shared_proto_user_v1_user_proto_rawDescGZIP() []byte {
	file_shared_proto_user_v1_user_proto_rawDescOnce.Do(func() {
		file_shared_proto_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_user_v1_user_proto_rawDesc), len(file_shared_proto_user_v1_user_proto_rawDesc)))
	})
	return file_shared_proto_user_v1_user_proto_rawDescData
}

var file_shared_proto_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_proto_user_v1_user_proto_goTypes = []any{
	(*CheckBanRequest)(nil),       // 0: user.v1.CheckBanRequest
	(*CheckBanResponse)(nil),      // 1: user.v1.CheckBanResponse
	(*GetFriendshipRequest)(nil),  // 2: user.v1.GetFriendshipRequest
	(*GetFriendshipResponse)(nil), // 3: user.v1.GetFriendshipResponse
	(*GetMutesRequest)(nil),       // 4: user.v1.GetMutesRequest
	(*GetMutesResponse)(nil),      // 5: user.v1.GetMutesResponse
}
var file_shared_proto_user_v1_user_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.CheckBan:input_type -> user.v1.CheckBanRequest
	2, // 1: user.v1.UserService.GetFriendship:input_type -> user.v1.GetFriendshipRequest
	4, // 2: user.v1.UserService.GetMutes:input_type -> user.v1.GetMutesRequest
	1, // 3: user.v1.UserService.CheckBan:output_type -> user.v1.CheckBanResponse
	3, // 4: user.v1.UserService.GetFriendship:output_type -> user.v1.GetFriendshipResponse
	5, // 5: user.v1.UserService.GetMutes:output_type -> user.v1.GetMutesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_user_v1_user_proto_init() }
func file_shared_proto_user_v1_user_proto_init() {
	if File_shared_proto_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_user_v1_user_proto_rawDesc), len(file_shared_proto_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_user_v1_user_proto_goTypes,
		DependencyIndexes: file_shared_proto_user_v1_user_proto_depIdxs,
		MessageInfos:      file_shared_proto_user_v1_user_proto_msgTypes,
	}.Build()
	File_shared_proto_user_v1_user_proto = out.File
	file_shared_proto_user_v1_user_proto_goTypes = nil
	file_shared_proto_user_v1_user_proto_depIdxs = nil
}
