// UserService — owned by user-service.
// Used by: game-server (ban check on login + WS connect,
//                        mute list for chat filtering,
//                        friendship status for DM/room join validation)
//
// Only exposes what other services need. Write operations (ban, report,
// friendship mutations) are HTTP-only, handled by user-service REST API.
// gRPC here is read-only + lightweight presence checks.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: shared/proto/user/v1/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CheckBan_FullMethodName      = "/user.v1.UserService/CheckBan"
	UserService_GetFriendship_FullMethodName = "/user.v1.UserService/GetFriendship"
	UserService_GetMutes_FullMethodName      = "/user.v1.UserService/GetMutes"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// CheckBan is called on login and WebSocket connect.
	// Returns is_banned=false if no active ban exists (not an error).
	CheckBan(ctx context.Context, in *CheckBanRequest, opts ...grpc.CallOption) (*CheckBanResponse, error)
	// GetFriendship returns the relationship status between two players.
	// Used by game-server to gate DMs (allow_dms=friends_only) and
	// to prevent blocked players from joining the same room.
	GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error)
	// GetMutes returns all player IDs muted by the given player.
	// Called by game-server on WS connect to populate the in-memory mute set.
	GetMutes(ctx context.Context, in *GetMutesRequest, opts ...grpc.CallOption) (*GetMutesResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CheckBan(ctx context.Context, in *CheckBanRequest, opts ...grpc.CallOption) (*CheckBanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBanResponse)
	err := c.cc.Invoke(ctx, UserService_CheckBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFriendship(ctx context.Context, in *GetFriendshipRequest, opts ...grpc.CallOption) (*GetFriendshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendshipResponse)
	err := c.cc.Invoke(ctx, UserService_GetFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMutes(ctx context.Context, in *GetMutesRequest, opts ...grpc.CallOption) (*GetMutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMutesResponse)
	err := c.cc.Invoke(ctx, UserService_GetMutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// CheckBan is called on login and WebSocket connect.
	// Returns is_banned=false if no active ban exists (not an error).
	CheckBan(context.Context, *CheckBanRequest) (*CheckBanResponse, error)
	// GetFriendship returns the relationship status between two players.
	// Used by game-server to gate DMs (allow_dms=friends_only) and
	// to prevent blocked players from joining the same room.
	GetFriendship(context.Context, *GetFriendshipRequest) (*GetFriendshipResponse, error)
	// GetMutes returns all player IDs muted by the given player.
	// Called by game-server on WS connect to populate the in-memory mute set.
	GetMutes(context.Context, *GetMutesRequest) (*GetMutesResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CheckBan(context.Context, *CheckBanRequest) (*CheckBanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBan not implemented")
}
func (UnimplementedUserServiceServer) GetFriendship(context.Context, *GetFriendshipRequest) (*GetFriendshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendship not implemented")
}
func (UnimplementedUserServiceServer) GetMutes(context.Context, *GetMutesRequest) (*GetMutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMutes not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CheckBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckBan(ctx, req.(*CheckBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFriendship(ctx, req.(*GetFriendshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMutes(ctx, req.(*GetMutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBan",
			Handler:    _UserService_CheckBan_Handler,
		},
		{
			MethodName: "GetFriendship",
			Handler:    _UserService_GetFriendship_Handler,
		},
		{
			MethodName: "GetMutes",
			Handler:    _UserService_GetMutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/user/v1/user.proto",
}
