/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RateLimitedRouteImport } from './routes/rate-limited'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestErrorRouteImport } from './routes/test.error'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as ProfilePlayerIdRouteImport } from './routes/profile.$playerId'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as SessionsSessionIdHistoryRouteImport } from './routes/sessions.$sessionId.history'

const RateLimitedRoute = RateLimitedRouteImport.update({
  id: '/rate-limited',
  path: '/rate-limited',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test/error',
  path: '/test/error',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePlayerIdRoute = ProfilePlayerIdRouteImport.update({
  id: '/profile/$playerId',
  path: '/profile/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdHistoryRoute =
  SessionsSessionIdHistoryRouteImport.update({
    id: '/sessions/$sessionId/history',
    path: '/sessions/$sessionId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/rate-limited': typeof RateLimitedRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/profile/$playerId': typeof ProfilePlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/test/error': typeof TestErrorRoute
  '/sessions/$sessionId/history': typeof SessionsSessionIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/rate-limited': typeof RateLimitedRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/profile/$playerId': typeof ProfilePlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/test/error': typeof TestErrorRoute
  '/sessions/$sessionId/history': typeof SessionsSessionIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/rate-limited': typeof RateLimitedRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/profile/$playerId': typeof ProfilePlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/test/error': typeof TestErrorRoute
  '/sessions/$sessionId/history': typeof SessionsSessionIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design'
    | '/login'
    | '/rate-limited'
    | '/game/$sessionId'
    | '/profile/$playerId'
    | '/rooms/$roomId'
    | '/test/error'
    | '/sessions/$sessionId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/design'
    | '/login'
    | '/rate-limited'
    | '/game/$sessionId'
    | '/profile/$playerId'
    | '/rooms/$roomId'
    | '/test/error'
    | '/sessions/$sessionId/history'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design'
    | '/login'
    | '/rate-limited'
    | '/game/$sessionId'
    | '/profile/$playerId'
    | '/rooms/$roomId'
    | '/test/error'
    | '/sessions/$sessionId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
  RateLimitedRoute: typeof RateLimitedRoute
  GameSessionIdRoute: typeof GameSessionIdRoute
  ProfilePlayerIdRoute: typeof ProfilePlayerIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  TestErrorRoute: typeof TestErrorRoute
  SessionsSessionIdHistoryRoute: typeof SessionsSessionIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rate-limited': {
      id: '/rate-limited'
      path: '/rate-limited'
      fullPath: '/rate-limited'
      preLoaderRoute: typeof RateLimitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/error': {
      id: '/test/error'
      path: '/test/error'
      fullPath: '/test/error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$playerId': {
      id: '/profile/$playerId'
      path: '/profile/$playerId'
      fullPath: '/profile/$playerId'
      preLoaderRoute: typeof ProfilePlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/history': {
      id: '/sessions/$sessionId/history'
      path: '/sessions/$sessionId/history'
      fullPath: '/sessions/$sessionId/history'
      preLoaderRoute: typeof SessionsSessionIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
  RateLimitedRoute: RateLimitedRoute,
  GameSessionIdRoute: GameSessionIdRoute,
  ProfilePlayerIdRoute: ProfilePlayerIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  TestErrorRoute: TestErrorRoute,
  SessionsSessionIdHistoryRoute: SessionsSessionIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
