// shared/proto/game/v1/game.proto
//
// GameService — owned by game-service.
// Used by: match-service (start session after both players accept match)
//          replay-service (fetch move log for a finished session)
//          ws-gateway (TODO: IsParticipant once game-service is extracted)
//
// Note: real-time game actions (moves, pause, ready) go through the
// WebSocket → game-service directly, NOT through gRPC. gRPC here is
// only for control-plane operations initiated by other services.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: shared/proto/game/v1/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID — room must exist and be in 'waiting' status
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"` // "casual" | "ranked"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartSessionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StartSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID of the created game_session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMoveLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveLogRequest) Reset() {
	*x = GetMoveLogRequest{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveLogRequest) ProtoMessage() {}

func (x *GetMoveLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveLogRequest.ProtoReflect.Descriptor instead.
func (*GetMoveLogRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoveLogRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveNumber    int32                  `protobuf:"varint,1,opt,name=move_number,json=moveNumber,proto3" json:"move_number,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON-encoded engine.Move.Payload
	AppliedAt     string                 `protobuf:"bytes,4,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *Move) GetMoveNumber() int32 {
	if x != nil {
		return x.MoveNumber
	}
	return 0
}

func (x *Move) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Move) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Move) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

type GetMoveLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Moves         []*Move                `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveLogResponse) Reset() {
	*x = GetMoveLogResponse{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveLogResponse) ProtoMessage() {}

func (x *GetMoveLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveLogResponse.ProtoReflect.Descriptor instead.
func (*GetMoveLogResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetMoveLogResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMoveLogResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetMoveLogResponse) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type IsParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       // UUID
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsParticipantRequest) Reset() {
	*x = IsParticipantRequest{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantRequest) ProtoMessage() {}

func (x *IsParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantRequest.ProtoReflect.Descriptor instead.
func (*IsParticipantRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *IsParticipantRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *IsParticipantRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type IsParticipantResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsParticipant     bool                   `protobuf:"varint,1,opt,name=is_participant,json=isParticipant,proto3" json:"is_participant,omitempty"`             // true if player is seated in the room
	SpectatorsAllowed bool                   `protobuf:"varint,2,opt,name=spectators_allowed,json=spectatorsAllowed,proto3" json:"spectators_allowed,omitempty"` // value of room_settings.allow_spectators
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IsParticipantResponse) Reset() {
	*x = IsParticipantResponse{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantResponse) ProtoMessage() {}

func (x *IsParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantResponse.ProtoReflect.Descriptor instead.
func (*IsParticipantResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *IsParticipantResponse) GetIsParticipant() bool {
	if x != nil {
		return x.IsParticipant
	}
	return false
}

func (x *IsParticipantResponse) GetSpectatorsAllowed() bool {
	if x != nil {
		return x.SpectatorsAllowed
	}
	return false
}

type GetRoomPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomPlayersRequest) Reset() {
	*x = GetRoomPlayersRequest{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomPlayersRequest) ProtoMessage() {}

func (x *GetRoomPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetRoomPlayersRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomPlayersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []string               `protobuf:"bytes,1,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // UUIDs ordered by seat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomPlayersResponse) Reset() {
	*x = GetRoomPlayersResponse{}
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomPlayersResponse) ProtoMessage() {}

func (x *GetRoomPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_game_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetRoomPlayersResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_game_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoomPlayersResponse) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

var File_shared_proto_game_v1_game_proto protoreflect.FileDescriptor

const file_shared_proto_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x1fshared/proto/game/v1/game.proto\x12\agame.v1\"[\n" +
	"\x13StartSessionRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"5\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetMoveLogRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"}\n" +
	"\x04Move\x12\x1f\n" +
	"\vmove_number\x18\x01 \x01(\x05R\n" +
	"moveNumber\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"applied_at\x18\x04 \x01(\tR\tappliedAt\"q\n" +
	"\x12GetMoveLogResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12#\n" +
	"\x05moves\x18\x03 \x03(\v2\r.game.v1.MoveR\x05moves\"L\n" +
	"\x14IsParticipantRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"m\n" +
	"\x15IsParticipantResponse\x12%\n" +
	"\x0eis_participant\x18\x01 \x01(\bR\risParticipant\x12-\n" +
	"\x12spectators_allowed\x18\x02 \x01(\bR\x11spectatorsAllowed\"0\n" +
	"\x15GetRoomPlayersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"7\n" +
	"\x16GetRoomPlayersResponse\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\tR\tplayerIds2\xc4\x02\n" +
	"\vGameService\x12K\n" +
	"\fStartSession\x12\x1c.game.v1.StartSessionRequest\x1a\x1d.game.v1.StartSessionResponse\x12E\n" +
	"\n" +
	"GetMoveLog\x12\x1a.game.v1.GetMoveLogRequest\x1a\x1b.game.v1.GetMoveLogResponse\x12N\n" +
	"\rIsParticipant\x12\x1d.game.v1.IsParticipantRequest\x1a\x1e.game.v1.IsParticipantResponse\x12Q\n" +
	"\x0eGetRoomPlayers\x12\x1e.game.v1.GetRoomPlayersRequest\x1a\x1f.game.v1.GetRoomPlayersResponseB/Z-github.com/recess/shared/proto/game/v1;gamev1b\x06proto3"

var (
	file_shared_proto_game_v1_game_proto_rawDescOnce sync.Once
	file_shared_proto_game_v1_game_proto_rawDescData []byte
)

func file_shared_proto_game_v1_game_proto_rawDescGZIP() []byte {
	file_shared_proto_game_v1_game_proto_rawDescOnce.Do(func() {
		file_shared_proto_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_game_v1_game_proto_rawDesc), len(file_shared_proto_game_v1_game_proto_rawDesc)))
	})
	return file_shared_proto_game_v1_game_proto_rawDescData
}

var file_shared_proto_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shared_proto_game_v1_game_proto_goTypes = []any{
	(*StartSessionRequest)(nil),    // 0: game.v1.StartSessionRequest
	(*StartSessionResponse)(nil),   // 1: game.v1.StartSessionResponse
	(*GetMoveLogRequest)(nil),      // 2: game.v1.GetMoveLogRequest
	(*Move)(nil),                   // 3: game.v1.Move
	(*GetMoveLogResponse)(nil),     // 4: game.v1.GetMoveLogResponse
	(*IsParticipantRequest)(nil),   // 5: game.v1.IsParticipantRequest
	(*IsParticipantResponse)(nil),  // 6: game.v1.IsParticipantResponse
	(*GetRoomPlayersRequest)(nil),  // 7: game.v1.GetRoomPlayersRequest
	(*GetRoomPlayersResponse)(nil), // 8: game.v1.GetRoomPlayersResponse
}
var file_shared_proto_game_v1_game_proto_depIdxs = []int32{
	3, // 0: game.v1.GetMoveLogResponse.moves:type_name -> game.v1.Move
	0, // 1: game.v1.GameService.StartSession:input_type -> game.v1.StartSessionRequest
	2, // 2: game.v1.GameService.GetMoveLog:input_type -> game.v1.GetMoveLogRequest
	5, // 3: game.v1.GameService.IsParticipant:input_type -> game.v1.IsParticipantRequest
	7, // 4: game.v1.GameService.GetRoomPlayers:input_type -> game.v1.GetRoomPlayersRequest
	1, // 5: game.v1.GameService.StartSession:output_type -> game.v1.StartSessionResponse
	4, // 6: game.v1.GameService.GetMoveLog:output_type -> game.v1.GetMoveLogResponse
	6, // 7: game.v1.GameService.IsParticipant:output_type -> game.v1.IsParticipantResponse
	8, // 8: game.v1.GameService.GetRoomPlayers:output_type -> game.v1.GetRoomPlayersResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_game_v1_game_proto_init() }
func file_shared_proto_game_v1_game_proto_init() {
	if File_shared_proto_game_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_game_v1_game_proto_rawDesc), len(file_shared_proto_game_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_game_v1_game_proto_goTypes,
		DependencyIndexes: file_shared_proto_game_v1_game_proto_depIdxs,
		MessageInfos:      file_shared_proto_game_v1_game_proto_msgTypes,
	}.Build()
	File_shared_proto_game_v1_game_proto = out.File
	file_shared_proto_game_v1_game_proto_goTypes = nil
	file_shared_proto_game_v1_game_proto_depIdxs = nil
}
