// shared/proto/game/v1/game.proto
//
// GameService — owned by game-service.
// Used by: match-service (start session after both players accept match)
//          replay-service (fetch move log for a finished session)
//          ws-gateway (TODO: IsParticipant once game-service is extracted)
//
// Note: real-time game actions (moves, pause, ready) go through the
// WebSocket → game-service directly, NOT through gRPC. gRPC here is
// only for control-plane operations initiated by other services.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: game.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_StartSession_FullMethodName  = "/game.v1.GameService/StartSession"
	GameService_GetMoveLog_FullMethodName    = "/game.v1.GameService/GetMoveLog"
	GameService_IsParticipant_FullMethodName = "/game.v1.GameService/IsParticipant"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// StartSession is called by match-service after both players accept.
	// Creates the game_session row and starts the ready-handshake timer.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// GetMoveLog is called by replay-service to fetch the ordered move list.
	GetMoveLog(ctx context.Context, in *GetMoveLogRequest, opts ...grpc.CallOption) (*GetMoveLogResponse, error)
	// IsParticipant is called by ws-gateway before upgrading a room WebSocket
	// connection to determine participant vs spectator status without reading
	// Postgres directly.
	IsParticipant(ctx context.Context, in *IsParticipantRequest, opts ...grpc.CallOption) (*IsParticipantResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, GameService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetMoveLog(ctx context.Context, in *GetMoveLogRequest, opts ...grpc.CallOption) (*GetMoveLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMoveLogResponse)
	err := c.cc.Invoke(ctx, GameService_GetMoveLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) IsParticipant(ctx context.Context, in *IsParticipantRequest, opts ...grpc.CallOption) (*IsParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsParticipantResponse)
	err := c.cc.Invoke(ctx, GameService_IsParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	// StartSession is called by match-service after both players accept.
	// Creates the game_session row and starts the ready-handshake timer.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// GetMoveLog is called by replay-service to fetch the ordered move list.
	GetMoveLog(context.Context, *GetMoveLogRequest) (*GetMoveLogResponse, error)
	// IsParticipant is called by ws-gateway before upgrading a room WebSocket
	// connection to determine participant vs spectator status without reading
	// Postgres directly.
	IsParticipant(context.Context, *IsParticipantRequest) (*IsParticipantResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedGameServiceServer) GetMoveLog(context.Context, *GetMoveLogRequest) (*GetMoveLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMoveLog not implemented")
}
func (UnimplementedGameServiceServer) IsParticipant(context.Context, *IsParticipantRequest) (*IsParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsParticipant not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetMoveLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMoveLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetMoveLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetMoveLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetMoveLog(ctx, req.(*GetMoveLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_IsParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).IsParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_IsParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).IsParticipant(ctx, req.(*IsParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _GameService_StartSession_Handler,
		},
		{
			MethodName: "GetMoveLog",
			Handler:    _GameService_GetMoveLog_Handler,
		},
		{
			MethodName: "IsParticipant",
			Handler:    _GameService_IsParticipant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
