// shared/proto/rating/v1/rating.proto
//
// RatingService — owned by rating-service.
// Consumers:
//   match-service  → GetRating (read MMR on ranked queue enqueue)
//   ws-gateway     → (future) GetLeaderboard for lobby display
//   frontend       → leaderboard via HTTP transcoding (future)
//
// Rating updates are NOT exposed via gRPC. They are triggered by the
// game.session.finished Redis event consumed internally by rating-service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: shared/proto/rating/v1/rating.proto

package ratingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // UUID
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`       // e.g. "tictactoe"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingRequest) Reset() {
	*x = GetRatingRequest{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingRequest) ProtoMessage() {}

func (x *GetRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingRequest.ProtoReflect.Descriptor instead.
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatingRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetRatingRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Mmr           float64                `protobuf:"fixed64,3,opt,name=mmr,proto3" json:"mmr,omitempty"` // hidden — do not expose to browser clients
	DisplayRating float64                `protobuf:"fixed64,4,opt,name=display_rating,json=displayRating,proto3" json:"display_rating,omitempty"`
	GamesPlayed   int32                  `protobuf:"varint,5,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	WinStreak     int32                  `protobuf:"varint,6,opt,name=win_streak,json=winStreak,proto3" json:"win_streak,omitempty"`
	LossStreak    int32                  `protobuf:"varint,7,opt,name=loss_streak,json=lossStreak,proto3" json:"loss_streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingResponse) Reset() {
	*x = GetRatingResponse{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingResponse) ProtoMessage() {}

func (x *GetRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingResponse.ProtoReflect.Descriptor instead.
func (*GetRatingResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatingResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetRatingResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetRatingResponse) GetMmr() float64 {
	if x != nil {
		return x.Mmr
	}
	return 0
}

func (x *GetRatingResponse) GetDisplayRating() float64 {
	if x != nil {
		return x.DisplayRating
	}
	return 0
}

func (x *GetRatingResponse) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *GetRatingResponse) GetWinStreak() int32 {
	if x != nil {
		return x.WinStreak
	}
	return 0
}

func (x *GetRatingResponse) GetLossStreak() int32 {
	if x != nil {
		return x.LossStreak
	}
	return 0
}

type GetRatingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []string               `protobuf:"bytes,1,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // max 100
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingsRequest) Reset() {
	*x = GetRatingsRequest{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingsRequest) ProtoMessage() {}

func (x *GetRatingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingsRequest.ProtoReflect.Descriptor instead.
func (*GetRatingsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{2}
}

func (x *GetRatingsRequest) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *GetRatingsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*GetRatingResponse   `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingsResponse) Reset() {
	*x = GetRatingsResponse{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingsResponse) ProtoMessage() {}

func (x *GetRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingsResponse.ProtoReflect.Descriptor instead.
func (*GetRatingsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{3}
}

func (x *GetRatingsResponse) GetRatings() []*GetRatingResponse {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // default 100, max 500
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // 0-based
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderboardRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"` // 1-based position (offset + index + 1)
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayRating float64                `protobuf:"fixed64,3,opt,name=display_rating,json=displayRating,proto3" json:"display_rating,omitempty"`
	GamesPlayed   int32                  `protobuf:"varint,4,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaderboardEntry) GetDisplayRating() float64 {
	if x != nil {
		return x.DisplayRating
	}
	return 0
}

func (x *LeaderboardEntry) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // total qualifying rows (for pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rating_v1_rating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rating_v1_rating_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeaderboardResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_shared_proto_rating_v1_rating_proto protoreflect.FileDescriptor

const file_shared_proto_rating_v1_rating_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/rating/v1/rating.proto\x12\trating.v1\"H\n" +
	"\x10GetRatingRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"\xe5\x01\n" +
	"\x11GetRatingResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03mmr\x18\x03 \x01(\x01R\x03mmr\x12%\n" +
	"\x0edisplay_rating\x18\x04 \x01(\x01R\rdisplayRating\x12!\n" +
	"\fgames_played\x18\x05 \x01(\x05R\vgamesPlayed\x12\x1d\n" +
	"\n" +
	"win_streak\x18\x06 \x01(\x05R\twinStreak\x12\x1f\n" +
	"\vloss_streak\x18\a \x01(\x05R\n" +
	"lossStreak\"K\n" +
	"\x11GetRatingsRequest\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\tR\tplayerIds\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"L\n" +
	"\x12GetRatingsResponse\x126\n" +
	"\aratings\x18\x01 \x03(\v2\x1c.rating.v1.GetRatingResponseR\aratings\"^\n" +
	"\x15GetLeaderboardRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8d\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12%\n" +
	"\x0edisplay_rating\x18\x03 \x01(\x01R\rdisplayRating\x12!\n" +
	"\fgames_played\x18\x04 \x01(\x05R\vgamesPlayed\"~\n" +
	"\x16GetLeaderboardResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.rating.v1.LeaderboardEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2\xf9\x01\n" +
	"\rRatingService\x12F\n" +
	"\tGetRating\x12\x1b.rating.v1.GetRatingRequest\x1a\x1c.rating.v1.GetRatingResponse\x12I\n" +
	"\n" +
	"GetRatings\x12\x1c.rating.v1.GetRatingsRequest\x1a\x1d.rating.v1.GetRatingsResponse\x12U\n" +
	"\x0eGetLeaderboard\x12 .rating.v1.GetLeaderboardRequest\x1a!.rating.v1.GetLeaderboardResponseB3Z1github.com/recess/shared/proto/rating/v1;ratingv1b\x06proto3"

var (
	file_shared_proto_rating_v1_rating_proto_rawDescOnce sync.Once
	file_shared_proto_rating_v1_rating_proto_rawDescData []byte
)

func file_shared_proto_rating_v1_rating_proto_rawDescGZIP() []byte {
	file_shared_proto_rating_v1_rating_proto_rawDescOnce.Do(func() {
		file_shared_proto_rating_v1_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_rating_v1_rating_proto_rawDesc), len(file_shared_proto_rating_v1_rating_proto_rawDesc)))
	})
	return file_shared_proto_rating_v1_rating_proto_rawDescData
}

var file_shared_proto_rating_v1_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shared_proto_rating_v1_rating_proto_goTypes = []any{
	(*GetRatingRequest)(nil),       // 0: rating.v1.GetRatingRequest
	(*GetRatingResponse)(nil),      // 1: rating.v1.GetRatingResponse
	(*GetRatingsRequest)(nil),      // 2: rating.v1.GetRatingsRequest
	(*GetRatingsResponse)(nil),     // 3: rating.v1.GetRatingsResponse
	(*GetLeaderboardRequest)(nil),  // 4: rating.v1.GetLeaderboardRequest
	(*LeaderboardEntry)(nil),       // 5: rating.v1.LeaderboardEntry
	(*GetLeaderboardResponse)(nil), // 6: rating.v1.GetLeaderboardResponse
}
var file_shared_proto_rating_v1_rating_proto_depIdxs = []int32{
	1, // 0: rating.v1.GetRatingsResponse.ratings:type_name -> rating.v1.GetRatingResponse
	5, // 1: rating.v1.GetLeaderboardResponse.entries:type_name -> rating.v1.LeaderboardEntry
	0, // 2: rating.v1.RatingService.GetRating:input_type -> rating.v1.GetRatingRequest
	2, // 3: rating.v1.RatingService.GetRatings:input_type -> rating.v1.GetRatingsRequest
	4, // 4: rating.v1.RatingService.GetLeaderboard:input_type -> rating.v1.GetLeaderboardRequest
	1, // 5: rating.v1.RatingService.GetRating:output_type -> rating.v1.GetRatingResponse
	3, // 6: rating.v1.RatingService.GetRatings:output_type -> rating.v1.GetRatingsResponse
	6, // 7: rating.v1.RatingService.GetLeaderboard:output_type -> rating.v1.GetLeaderboardResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_rating_v1_rating_proto_init() }
func file_shared_proto_rating_v1_rating_proto_init() {
	if File_shared_proto_rating_v1_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_rating_v1_rating_proto_rawDesc), len(file_shared_proto_rating_v1_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_rating_v1_rating_proto_goTypes,
		DependencyIndexes: file_shared_proto_rating_v1_rating_proto_depIdxs,
		MessageInfos:      file_shared_proto_rating_v1_rating_proto_msgTypes,
	}.Build()
	File_shared_proto_rating_v1_rating_proto = out.File
	file_shared_proto_rating_v1_rating_proto_goTypes = nil
	file_shared_proto_rating_v1_rating_proto_depIdxs = nil
}
